version: "2.1"
services:
  udpraw:
    env_file:
      - ./.env
    depends_on:
      - udp-speeder
    build: .
    expose:
      - "4444/udp"
    image: udp-speeder
    restart: always
    privileged: true
    networks:
      wireguard:
        ipv4_address: ${UDP_RAW_IP}
    sysctls:
      - net.ipv4.conf.default.forwarding=1
      - net.ipv4.conf.all.forwarding=1
    command: ./udp2raw_amd64 -c -l0.0.0.0:4444 -r ${SERVER_ADDRESS}:${SERVER_PORT} --raw-mode  icmp -k "${PASSWORD}" -a
  udp-speeder:
    env_file:
      - ./.env
    build: .
    image: udp-speeder
    restart: always
    ports:
      - "${SERVER_PORT}:4444/udp"
    networks:
      wireguard:
        ipv4_address: ${UDP_SPEEDER_IP}
    command: ./speederv2_amd64 -c -l0.0.0.0:4444 -r 10.5.0.3:4444  -f20:10 -k "${PASSWORD}"
networks:
  wireguard:
    driver: bridge
    ipam:
     config:
       - subnet: ${SUBNET}/16
         gateway: ${GATEWAY}
